In [1]:
import pandas as pd
import numpy as np

In [2]:
from acquire import get_titanic_data
from prepare import prep_titanic
import warnings
warnings.filterwarnings('ignore')
from sklearn.tree import DecisionTreeClassifier,plot_tree,export_text
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression


In [3]:
df = get_titanic_data()
train, validate, test  = prep_titanic(df)

In [4]:
dummy_df

NameError: name 'dummy_df' is not defined

In [5]:
drops = ['sex','Unnamed: 0','age']

In [6]:
[dataset.drop(columns=drops, inplace=True) for dataset in [train, validate, test,]]

[None, None, None]

In [7]:
train.columns

Index(['survived', 'fare', 'alone', 'is_adult', 'sex_female', 'sex_male',
       'class_First', 'class_Second', 'class_Third'],
      dtype='object')

In [8]:
train.survived.value_counts()

0    254
1    172
Name: survived, dtype: int64

In [9]:
x_train = train.drop(columns = 'survived')
y_train = train.survived
x_validate = validate.drop(columns = 'survived')
y_validate = validate.survived
x_test = test.drop(columns = 'survived')
y_test = test.survived

In [10]:
baseline = (y_train == 0).mean()

In [11]:
print('our baseline accuracy for nonsurvival is:', baseline)

our baseline accuracy for nonsurvival is: 0.596244131455399


In [12]:
clf = DecisionTreeClassifier()

In [13]:
clf.fit(x_train,y_train)

DecisionTreeClassifier()

In [14]:
clf.score(x_train,y_train)

0.9342723004694836

In [15]:
clf.predict(x_train)

array([0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0,

In [16]:
y_preds = pd.DataFrame({
 'y_act': y_train,
'baseline': 0,
'model_1': clf.predict(x_train)})

In [17]:
y_preds

y_act  baseline  model_1
104      0         0        0
379      0         0        0
682      0         0        0
432      1         0        1
890      0         0        0
..     ...       ...      ...
472      1         0        1
310      1         0        1
341      1         0        1
72       0         0        0
749      0         0        0

[426 rows x 3 columns]

In [18]:
acc = clf.score(x_train, y_train)
accuracy_score(y_preds.y_act, y_preds.model_1)

0.9342723004694836

In [19]:
acc

0.9342723004694836

In [20]:
pd.DataFrame(classification_report(y_preds.y_act, y_preds.model_1, output_dict=True))

0           1  accuracy   macro avg  weighted avg
precision    0.921642    0.955696  0.934272    0.938669      0.935391
recall       0.972441    0.877907  0.934272    0.925174      0.934272
f1-score     0.946360    0.915152  0.934272    0.930756      0.933759
support    254.000000  172.000000  0.934272  426.000000    426.000000

In [21]:
conf = confusion_matrix(y_preds.y_act, y_preds.model_1)

In [22]:
conf

array([[247,   7],
       [ 21, 151]])

In [23]:
rubric_df = pd.DataFrame({
    'pred_death': ['True Negative', 'False Negative'],
    'pred_survive':['False Positive','True Positive']
    }, index=['actual_death', 'actual_survive'])

In [24]:
rubric_df

pred_death    pred_survive
actual_death     True Negative  False Positive
actual_survive  False Negative   True Positive

In [25]:
rubric_df + ': ' + conf.astype(str)

pred_death        pred_survive
actual_death    True Negative: 247   False Positive: 7
actual_survive  False Negative: 21  True Positive: 151

In [26]:
TN = conf[0,0]
FP = conf[0,1]
FN = conf[1,0]
TP = conf[1,1]
TN, FP, FN, TP

(247, 7, 21, 151)

In [ ]:
clf2 = DecisionTreeClassifier(max_depth=4)

In [ ]:
clf2.fit(x_train,y_train)

In [ ]:
y_preds['model2'] = clf2.predict(x_train)

In [ ]:
clf2.score(x_train, y_train)

In [ ]:
#################################################################################################################

In [ ]:
#                                  Decision Forest


In [ ]:
x_train.head()

In [ ]:
rf = RandomForestClassifier(min_samples_leaf = 1,max_depth = 10, random_state = 123)

In [ ]:
rf.fit(x_train,y_train)

In [ ]:
y_pred = rf.predict(x_train)

In [ ]:
y_pred_proba = rf.predict_proba(x_train)

In [ ]:
y_pred_proba

In [ ]:
print('Accuracy of random forest classifier on training set: {:.2f}'
     .format(rf.score(x_train, y_train)))

In [ ]:
conf = confusion_matrix(y_train,y_pred)
conf

In [ ]:
disp = ConfusionMatrixDisplay(confusion_matrix=conf, display_labels=rf.classes_)

disp.plot()
plt.show()


In [ ]:
print(classification_report(y_train,y_pred))

In [ ]:
rf2 = RandomForestClassifier(min_samples_leaf = 4,max_depth = 8, random_state = 123)

In [ ]:
rf2.fit(x_train,y_train)

In [ ]:
y_pred2 = rf2.predict(x_train)

In [ ]:
y_pred_proba2 = rf.predict_proba(x_train)

In [ ]:
print('Accuracy of random forest classifier on training set: {:.2f}'
     .format(rf2.score(x_train, y_train)))

In [ ]:
disp = ConfusionMatrixDisplay(confusion_matrix=conf, display_labels=rf2.classes_)

disp.plot()
plt.show()



In [ ]:
TP = 179
TN = 26
FP = 6
FN = 323

In [ ]:
print(classification_report(y_train, y_pred2))

In [ ]:
rf3 = RandomForestClassifier(min_samples_leaf = 6,max_depth = 6, random_state = 123)

In [ ]:
rf3.fit(x_train,y_train)

In [ ]:
y_pred3 = rf3.predict(x_train)

In [ ]:
print('Accuracy of random forest classifier on training set: {:.2f}'
     .format(rf3.score(x_train, y_train)))

In [ ]:
print(classification_report(y_train, y_pred3))

In [ ]:
##############################TRAIN##############################################################

In [ ]:
#first forest (min =1 max =10)
print('Accuracy of random forest classifier on validate set: {:.2f}'
     .format(rf.score(x_train, y_train)))

In [ ]:
#second forest (min =4 max = 8)
print('Accuracy of random forest classifier on validate set: {:.2f}'
     .format(rf2.score(x_train, y_train)))

In [ ]:
#second forest (min =6 max = 6)
print('Accuracy of random forest classifier on validate set: {:.2f}'
     .format(rf3.score(x_train, y_train)))

In [ ]:
##############################VALIDATE#################################################

In [ ]:
#first forest (min =1 max =10)
print('Accuracy of random forest classifier on validate set: {:.2f}'
     .format(rf.score(x_validate, y_validate)))

In [ ]:
#second forest (min =4 max = 8)
print('Accuracy of random forest classifier on validate set: {:.2f}'
     .format(rf2.score(x_validate, y_validate)))

In [ ]:
#THird forest (min =6 max = 6)
print('Accuracy of random forest classifier on validate set: {:.2f}'
     .format(rf3.score(x_validate, y_validate)))

In [ ]:
###########################CLASSIFICATION REPORTS#####################################################

In [ ]:
#first forest (min =1 max =10)
print(classification_report(y_train, y_pred))

In [ ]:
#second forest (min =4 max = 8)
print(classification_report(y_train,y_pred2))

In [ ]:
#Third Forest (min = 6, max = 6)
print(classification_report(y_train,y_pred3))

In [ ]:
#Second forest is the most consistant

In [ ]:
#-------------------------------------KNN exercises----------------------------------------------------------------

In [ ]:
knn = KNeighborsClassifier(n_neighbors = 8)

In [ ]:
knn.fit(x_train,y_train)

In [ ]:
y_pred = knn.predict(x_train)

In [ ]:
train.survived.unique()

In [ ]:
confusion_matrix(y_train, y_pred)

In [ ]:
pd.crosstab(y_train, y_pred)

In [ ]:
print(classification_report(y_train, y_pred))

In [ ]:
tn, fp, fn, tp = confusion_matrix(y_train, y_pred).ravel()
all = tn + fp + fn + tp

In [ ]:
for i in range(2,21):
    knn = KNeighborsClassifier(n_neighbors = i)
    knn.fit(x_train,y_train)
    y_pred = knn.predict(x_train)
    print('k used is: ', i)
    print(classification_report(y_train, y_pred))
    

In [ ]:
#=================================Logistic Regression============================================================

In [27]:
x_train

fare  alone  is_adult  sex_female  sex_male  class_First  \
104    7.9250      0         1           0         1            0   
379    7.7750      1         1           0         1            0   
682    9.2250      1         1           0         1            0   
432   26.0000      0         1           1         0            0   
890    7.7500      1         1           0         1            0   
..        ...    ...       ...         ...       ...          ...   
472   27.7500      0         1           1         0            0   
310   83.1583      1         1           1         0            1   
341  263.0000      0         1           1         0            1   
72    73.5000      1         1           0         1            0   
749    7.7500      1         1           0         1            0   

     class_Second  class_Third  
104             0            1  
379             0            1  
682             0            1  
432             1            0  
890             0            1  
..            ...          ...  
472             1            0  
310             0            0  
341             0            0  
72              1            0  
749             0            1  

[426 rows x 8 columns]

In [28]:
logreg = LogisticRegression()


In [46]:
logreg2 = LogisticRegression(C = .3)

In [47]:
logreg.fit(x_train,y_train)
logreg2.fit(x_train,y_train)


LogisticRegression(C=0.3)

In [48]:
y_pred = logreg.predict(x_train)
y_pred2 = logreg2.predict(x_train)

In [53]:

y_pred[:5]

array([0, 0, 0, 1, 0])

In [33]:
logreg.classes_

array([0, 1])

In [55]:
y_pred_proba = logreg.predict_proba(x_train)
y_pred_proba = pd.DataFrame(y_pred_proba, columns = ['died', 'survived'])
y_pred_proba2 = logreg2.predict_proba(x_train)
y_pred_proba2 = pd.DataFrame(y_pred_proba2, columns = ['died','survived'])

In [36]:
#model 1
y_pred_proba

died  survived
0    0.938321  0.061679
1    0.937366  0.062634
2    0.937112  0.062888
3    0.202251  0.797749
4    0.937370  0.062630
..        ...       ...
421  0.201414  0.798586
422  0.094796  0.905204
423  0.058778  0.941222
424  0.714485  0.285515
425  0.937370  0.062630

[426 rows x 2 columns]

In [56]:
#model 2
y_pred_proba2

died  survived
0    0.915314  0.084686
1    0.919253  0.080747
2    0.918825  0.081175
3    0.221348  0.778652
4    0.919260  0.080740
..        ...       ...
421  0.220154  0.779846
422  0.121888  0.878112
423  0.060697  0.939303
424  0.693897  0.306103
425  0.919260  0.080740

[426 rows x 2 columns]

In [37]:
#MOdel 1
print(classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           0       0.79      0.92      0.85       254
           1       0.84      0.63      0.72       172

    accuracy                           0.81       426
   macro avg       0.82      0.78      0.79       426
weighted avg       0.81      0.81      0.80       426



In [58]:
#model 2
print(classification_report(y_train, y_pred2))

              precision    recall  f1-score   support

           0       0.79      0.92      0.85       254
           1       0.85      0.64      0.73       172

    accuracy                           0.81       426
   macro avg       0.82      0.78      0.79       426
weighted avg       0.81      0.81      0.80       426



In [39]:
logreg.coef_

array([[ 0.00296831,  0.01684144, -0.93811916,  1.22343803, -1.22395051,
         0.99605364,  0.29841821, -1.29498432]])

In [41]:
x_train

fare  alone  is_adult  sex_female  sex_male  class_First  \
104    7.9250      0         1           0         1            0   
379    7.7750      1         1           0         1            0   
682    9.2250      1         1           0         1            0   
432   26.0000      0         1           1         0            0   
890    7.7500      1         1           0         1            0   
..        ...    ...       ...         ...       ...          ...   
472   27.7500      0         1           1         0            0   
310   83.1583      1         1           1         0            1   
341  263.0000      0         1           1         0            1   
72    73.5000      1         1           0         1            0   
749    7.7500      1         1           0         1            0   

     class_Second  class_Third  
104             0            1  
379             0            1  
682             0            1  
432             1            0  
890             0            1  
..            ...          ...  
472             1            0  
310             0            0  
341             0            0  
72              1            0  
749             0            1  

[426 rows x 8 columns]

In [43]:
#MODEL 1 coeffs
log_coeffs = pd.DataFrame(logreg.coef_[0], index=x_train.columns,
                         columns=['coeff'])
log_coeffs

coeff
fare          0.002968
alone         0.016841
is_adult     -0.938119
sex_female    1.223438
sex_male     -1.223951
class_First   0.996054
class_Second  0.298418
class_Third  -1.294984

In [59]:
#model 2 coeff
log_coeffs2 = pd.DataFrame(logreg2.coef_[0], index = x_train.columns, columns = ['coeff'])
log_coeffs2

coeff
fare          0.003966
alone        -0.051327
is_adult     -0.691877
sex_female    1.104217
sex_male     -1.109070
class_First   0.810431
class_Second  0.268944
class_Third  -1.084228

In [44]:
#model 1 odds
odds = np.exp(log_coeffs)
odds

coeff
fare          1.002973
alone         1.016984
is_adult      0.391363
sex_female    3.398853
sex_male      0.294066
class_First   2.707576
class_Second  1.347725
class_Third   0.273902

In [60]:
odds2 = np.exp(log_coeffs2)
odds2

coeff
fare          1.003974
alone         0.949968
is_adult      0.500636
sex_female    3.016862
sex_male      0.329866
class_First   2.248876
class_Second  1.308582
class_Third   0.338163

In [61]:
#model1 validate
print(classification_report(y_validate, logreg.predict(x_validate)))

              precision    recall  f1-score   support

           0       0.74      0.89      0.81        85
           1       0.78      0.53      0.63        58

    accuracy                           0.75       143
   macro avg       0.76      0.71      0.72       143
weighted avg       0.75      0.75      0.74       143



In [62]:
#model2 validate
print(classification_report(y_validate, logreg2.predict(x_validate)))

              precision    recall  f1-score   support

           0       0.74      0.91      0.81        85
           1       0.79      0.53      0.64        58

    accuracy                           0.76       143
   macro avg       0.77      0.72      0.73       143
weighted avg       0.76      0.76      0.74       143

